const typed = new Typed('.multiple-text', {
    strings:    ["géniale", 
                "motivée",
                "extraordinaire",
                "parfaite",
                "celle qui fait le site",
                "époustouflante",
                "modeste",
                "magnifique",
                "charismatique",
                "toujours celle qui fait le site",
                "lumineuse",
                "merveilleuse",
                "remarquable",
                "talentueuse",
                "rncore celle qui fait le site",
                "modeste",
                "précieuse",
                "prodigieuse",
                "généreuse",
                "",
                ],
    typeSpeed: 100,
    backSpeed: 100,
    backDelay: 1000,
    loop: true,        
});